---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuropipeline-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neuropipeline-app
  template:
    metadata:
      labels:
        app: neuropipeline-app
    spec:
      containers:
      - name: neuro-container
        image: mlops-agent:v2  #my docker image name
        imagePullPolicy: Never #  use local image without pulling from registry
        ports:
        - containerPort: 8501  # the streamlit app runs on this port

---
# service opens port 80 and forwards to the deployment's port 8501
apiVersion: v1
kind: Service
metadata:
  name: neuropipeline-app
spec:
  selector:
    app: neuropipeline-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501

---
# ingress routes external traffic to the service based on host and path
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: neuropipeline-app-ingress
spec:
  tls:
  - hosts:
    - neuropipeline-app
    secretName: neuroapp-tls
  rules:
  - host: neuropipeline-app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: neuropipeline-app
            port:
              number: 80